#!/bin/bash
# Simple script to create a new text file to write a diary entry in.

DEVICE_NAME="$(hostname)"
TIMESTAMP="$(date +%s)"
FILE_NAME="diary-${TIMESTAMP}-${DEVICE_NAME}.txt"

DIARY_DIRECTORY="${HOME}/.diary/data/entries"
FILE_PATH="${DIARY_DIRECTORY}/${FILE_NAME}"

function use_gedit {
    gedit --new-window $FILE_PATH + &
}

function use_cat {
    cat >> $FILE_PATH 
}

function use_vim {
    vim "+set spell" $FILE_PATH
}

function usage_and_exit {
    echo "Help not implemented yet."
}

if [ $# = 0 ] ; then 
    use_vim
    exit
fi

case "$1" in
    -c | --cat ) use_cat ;;
    -g | --gedit ) use_gedit ;;
    -v | --vim ) use_vim ;;
    * ) usage_and_exit ;;
esac

