#!/bin/bash
# Script to search diary entries for tags or sequences of words or quoted text. 

DIARY_DIR="${HOME}/.diary/backup/dropbox/data/entries"
SEP="\e[0;34m"$(hline)"\e[0m"

function search_tags {
	[ $# == 0 ] && exit 1
	search_string="\(#$1\)"
	shift
	for tag in "$@"; do 
		search_string=$search_string"\|\(#$tag\)"
	done

	for entry in $(ls $DIARY_DIR -r); do
		if grep -qi "$search_string" $DIARY_DIR/$entry; then 
		fold -s -w $(tput cols) $DIARY_DIR/$entry | grep --colour=always -i "\|$search_string" 
		echo -e $SEP
		fi
	done | less -R
}

function search_words {
	#TODO
	echo words
}

function search_quoted {
	#TODO
	echo quoted
}

function search_default {
	search_tags $@
}


function usage_and_exit {
        echo "Help not implemented yet."
        exit
}

# If no arguments then quit.
if [ $# == 0 ] ; then 
	usage_and_exit
        exit
fi

# Decide what the user is searching for.
case $1 in 
	-t | --tags ) shift; search_tags $@ ;;
	-w | --words ) shift; search_words $@ ;;
	-q | --quoted ) shift; search_quoted $@ ;;
	* ) search_default $@ ;;
esac
