#!/bin/bash
# Quick script to strip the dates from early entries. 

cd "${HOME}/.diary/data/entries"

for entry in *; do 
	awk 'FNR>1' $entry > ${entry}.stripped
	mv ${entry}{,.bak}
	mv ${entry}.stripped $entry
done
