#!/usr/bin/env python
# Script to convert multiple diary entries in one file to multiple files contianing one diary entry each. 

inputfile = open('/home/david/diarytest/originals/Diary1.txt', 'r')
emptylines = 0

for line in inputfile:
	line = line.rstrip('\r\n ')
	if line == '': 
		emptylines += 1
		print emptylines,
	elif emptylines == 1:
		print ''
	print line

inputfile.close()
