#!/bin/bash
# Script to launch the default editor on a specified diary entry.

# If no arguments then use the last entry, otherwise use the given arguments 
# as arguments to diary-range and edit the first entry that it returns.
if [[ "$#" == 0 ]]; then 
    entry_filename=$(diary-range "--range=-1::-1")
else
    entry_filename=$(diary-range "$@" | head -q --lines=1)
fi

# Get default editor and launch it on the filename. 
editor="$(diary-settings get diary_edit_default_editor)"
eval "$editor $entry_filename"
