#!/bin/bash
# Simple script to create a new text file to write a diary entry in.

# Determine file name and path.
device_name="$(hostname)"
timestamp="$(date +%s)"
file_name="diary-$timestamp-$device_name.txt"

diary_directory="$HOME/.diary/data/entries"
month=$(date '+%Y-%m')
file_path="$diary_directory/$month/$file_name"


use_gedit() {
    gedit --new-window "$file_path" + &
}

use_vim() {
    vim "+set spell" "+syntax off" "+startinsert" "$file_path"
}

# If no args then use Vim.
if [[ $# == 0 ]] ; then 
    use_vim
    exit
fi

# Process command line options.
case "$1" in
    -g | --gedit)
        use_gedit
    ;;
    -v | --vim)
        use_vim
    ;;
    *)
        exit 1
    ;;
esac
