#!/bin/bash
# Backs up all diary related data to multiple sources.

DIARY_DIR="${HOME}/.diary/backup/dropbox/data/entries"

# Set the default number of entries to show.
num_entries=50

while true; do
    case $1 in
        -n) 
            shift
            num_entries="$1"
            shift
        ;;
        --number=*)
            num_entries=${1#--number=}
            shift
        ;;
        -r | --reverse)
            reverse=true
            shift
        ;;
        *)
            break
        ;;
    esac
done

entries=$(ls -1r $DIARY_DIR | head --lines=$num_entries)
[[ $reverse ]] && entries=$(for entry in $entries; do echo $entry; done | sort)

for entry in $entries; do
    diary-format -m "$DIARY_DIR/$entry"
done | less -R
