#!/bin/bash
# Script to search diary entries for tags or sequences of words or quoted text. 

search_tags() {
    # Re-use search_words by prefixing each argument with a '#'.
    search_words $(for tag in $@; do echo "#$tag\S*"; done)  # TODO change so that it stops the highlight at certain chars.
}

search_words() {

    # Build search string.
    search_string="\($1\)"
    shift
    for word in "$@"; do 
    	search_string=$search_string"\|\($word\)"
    done

    num_matches=0

    for entry in $(diary-range -r "$range"); do
        
        # If the entry contains the search string.
        if grep -qi "$search_string" "$entry"; then 

            # Print the entry using diary-format.
            diary-format -m --search="$search_string" "$entry"
            
            # Keep track of the number of matches found so far.
            let 'num_matches++'
            if (( num_matches >= max_matches )); then 
                echo "$num_matches entries found, max search depth reached."
                return
            fi

        fi

    done

    # Useful information to help the user work out why there were no matches. 
    if (( num_matches == 0 )); then 
    	echo "No matches."
        echo "Range: $range"
        echo "Search term: $search_string"
    fi
}


# Process command line args.
print=
range="-200::-1"
max_matches=40
while true; do
    case "$1" in 
        --max-matches=*)
            max_matches="${1#--max-matches=}"
        ;;
        -p | --print)
            print=true
        ;;
        -r)
            shift
            range="$1"
            shift
        ;;
        --range=*)
            range="${1#--range=}"
            shift
        ;;
        -t | --tags)
            shift
            mode=tags
        ;;
        -w | --words)
            shift
            mode=words
        ;;
        *)
            break
        ;;
    esac
done

# If no arguments then search for all tags.
if [[ $# == 0 ]]; then 
    search_words '#\S*'  # TODO change to only search for specific character set.
    exit
fi

# Is the user searching for words or tags?
case "$mode" in
    tags)
        if [[ "$print" ]]; then
            search_tags "$@"
        else
            search_tags "$@" | less -R
        fi
    ;;
    words)
        if [[ "$print" ]]; then
            search_words "$@"
        else
            search_words "$@" | less -R
        fi
    ;;
esac
