#!/bin/bash
# The script that launches other diary related scripts.

function help_and_exit {
	echo "Help not implemented yet."
	exit 0
}

function usage_and_exit {
	echo "Usage not implemented yet."
	exit 1
}

# Default action to be taken if the script is run with no arguments.
if [[ $# == 0 ]]; then 
    diary-new-entry
    diary-backup > /dev/null &
	exit
fi

# Check for command.
case "$1" in
	backup | backu | back | bac | ba | b )
        shift
        diary-backup $@ 
    ;;
    edit | edi | ed | e )
        shift
        diary-edit $@ 
    ;;
	help | hel | he | h | -h | --help )
        shift
        help_and_exit $@ 
    ;;
	list | lis | li | l )
        shift
        diary-list $@ 
    ;;
    new | ne | n )
        shift
        diary-new-entry $@ 
    ;;
    search | searc | sear | sea | se | s )
        shift
        diary-search $@ 
    ;;
	* )
        usage_and_exit 
    ;;
esac

