#!/bin/bash
# The script that launches other diary related scripts.

help_and_exit() {
    # TODO
    echo "Help not implemented yet."
    exit 0
}

usage_and_exit() {
    # TODO
    echo "Usage not implemented yet."
    exit 1
}

# Find out which diary script was actually executed and then use the 
# corresponding subscripts. 
real_path=$(readlink -f $0)
real_path=${real_path%/*}

# Default action to be taken if the script is run with no arguments.
if [[ $# == 0 ]]; then 
    action="$(diary-settings get diary_default_action)"
    eval "$action"
    exit 0
fi

# Check for command.
case "$1" in
    # TODO add a command called cd that can change the current dir easily to 
    # one of the commonly used diary directories (e.g. .diary, data, entries).
    edit | edi | ed | e )
        shift
        source "$real_path/diary-edit" "$@"
        #diary-edit "$@" 
    ;;
    help | hel | he | h | -h | --help )
        shift
        help_and_exit "$@" 
    ;;
    list | lis | li | l | ls )
        shift
        source "$real_path/diary-search" --list "$@"
        #diary-search --list "$@"
    ;;
    new | ne | n )
        shift
        source "$real_path/diary-new-entry" "$@"
        #diary-new-entry "$@" 
    ;;
    search | searc | sear | sea | se | s )
        shift
        source "$real_path/diary-search" "$@"
        #diary-search "$@" 
    ;;
    wc | w | wordcount )
        shift
        source "$real_path/diary-wordcount" "$@"
        #diary-wordcount "$@"
    ;;
    * )
        usage_and_exit "$@"
    ;;
esac
