#!/bin/bash
# Quick script to sort current entries into directories (one dir per calendar month).

cd "${HOME}/.diary/data/entries"

for f in *; do 
    entry_date=${f#diary-}
    entry_date=${entry_date%%-*}
    entry_date=$(date +%Y-%m -d "@$entry_date")
    mkdir -pv "$entry_date"
    mv -Tnv "$f" "$entry_date/$f"
done
