import random

filler_text = '''Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Dolor laborum. et magna dolor nostrud Lorem qui deserunt do Excepteur laboris occaecat ut minim nisi dolore reprehenderit exercitation in eu quis aute aliquip laboris dolore deserunt cupidatat consequat. voluptate officia non irure commodo Duis amet, in mollit occaecat tempor ut sunt enim Excepteur sunt dolore minim do dolor fugiat voluptate Excepteur in adipisicing do undefined culpa cupidatat mollit proident, undefined commodo consectetur.
Labore deserunt aute incididunt amet, Excepteur labore qui velit ad Duis qui sint consequat. Ut dolore laboris mollit cillum reprehenderit aute non minim ad dolore Ut Excepteur reprehenderit sint aliqua. Duis reprehenderit culpa et Ut ipsum exercitation exercitation nulla ipsum ea ex in ullamco ea fugiat officia occaecat nulla nostrud cupidatat ea irure ad in ullamco culpa enim ullamco in enim in sed ad Ut velit dolor dolor eu.
Fugiat reprehenderit eiusmod adipisicing ad eiusmod sint aliquip id nostrud Duis aliquip labore ipsum mollit Ut Duis aute sit sed Ut dolor exercitation consequat. qui Duis velit aliquip nulla culpa non consequat. qui elit, amet, esse velit ea ad veniam, Excepteur aliqua. ut deserunt Ut aliquip deserunt elit, occaecat ullamco dolore aliquip voluptate laborum. elit, sit in dolore est.
Ullamco ut velit non culpa veniam, in consequat. nostrud sint amet, nulla in labore cillum non sed Ut veniam, dolor occaecat in do occaecat voluptate nostrud deserunt nisi labore in deserunt voluptate consectetur do quis exercitation nisi laboris eiusmod anim Ut reprehenderit occaecat magna nisi occaecat aliquip sed irure exercitation exercitation undefined adipisicing sint cupidatat eu labore sunt amet, officia Excepteur mollit sint magna sunt.
Aliqua. consectetur elit, Ut est officia veniam, nulla sint in ipsum dolore do aute fugiat exercitation aliquip commodo consequat. consectetur et do officia reprehenderit aute ut laboris quis culpa eu incididunt tempor reprehenderit ipsum aute veniam, aliqua. culpa Duis nostrud aute aliqua. id amet, sit aute id sunt laborum. velit nulla minim adipisicing tempor Duis est sint exercitation quis consequat. ut aliqua. eu reprehenderit.
Culpa Duis incididunt est elit, ea dolore tempor in occaecat non in pariatur. commodo sint commodo ut ut sit commodo reprehenderit ex eu laborum. magna non aliqua. eiusmod Excepteur enim deserunt velit veniam, et dolore eu cupidatat deserunt do irure eu sunt irure voluptate est officia undefined in occaecat labore dolor est mollit dolor incididunt in Excepteur.
Commodo nostrud pariatur. sit Excepteur est sunt culpa in dolore ex tempor cillum ut sint laboris Excepteur ut adipisicing laborum. enim pariatur. reprehenderit ut consectetur ad in dolore Excepteur velit ipsum adipisicing ex deserunt aliqua. cupidatat aliquip nisi sint consectetur laboris velit aliquip ex ullamco dolore in pariatur. non dolor ad velit nostrud veniam, laborum. esse laborum. dolor fugiat aute consequat. velit cillum qui in dolor.
Dolore ex nulla incididunt aute ut aute pariatur. est ipsum sunt occaecat quis ea dolor culpa aute esse id ex incididunt ad consectetur do ex mollit voluptate dolor enim dolor reprehenderit ut anim Duis dolor pariatur. aute velit consequat. in consequat. aliqua. aliquip est fugiat voluptate ad sit esse in adipisicing elit, dolor magna in dolor ullamco occaecat eu aliquip reprehenderit fugiat.
Ex qui Excepteur eiusmod Excepteur officia cillum id aliqua. ad in in minim quis ut culpa in irure nisi pariatur. magna nostrud aliquip eiusmod non occaecat dolor do quis non et ea quis dolor ut incididunt ea proident, Excepteur in tempor nisi sunt eu mollit consectetur mollit nostrud dolor in tempor ut nulla exercitation et dolore reprehenderit consectetur irure tempor sunt tempor elit, eiusmod in sit.
Sit commodo minim id eiusmod in Duis laboris Excepteur ut ea minim magna Duis deserunt velit veniam, proident, aliqua. dolore anim commodo ullamco do labore non ullamco non enim ipsum consectetur irure sint Lorem deserunt dolor commodo cillum velit dolore Excepteur laborum. in tempor anim mollit magna in quis consequat. non ex Duis undefined eiusmod pariatur. dolore dolor dolore pariatur. incididunt eiusmod Excepteur non id Duis et adipisicing in ea eu.
Sit aute nostrud ex laboris ad aliqua. est dolor commodo pariatur. anim Duis velit veniam, incididunt ullamco ad non dolore nisi esse pariatur. Excepteur ut mollit in aute sit anim tempor aliqua. cupidatat dolore ea cupidatat est consectetur Lorem nulla dolor velit ea commodo do officia incididunt nostrud in nostrud pariatur. occaecat anim.
Quis adipisicing fugiat sit sit tempor sit irure elit, consequat. non est est Ut non aute Duis magna eu labore ullamco et fugiat in veniam, dolor dolor sed tempor cupidatat proident, in ut eiusmod ad quis labore ad ipsum officia amet, non dolore nisi aute proident, deserunt Duis nulla Duis proident, sed est irure Ut minim dolor magna proident, magna ullamco commodo.
Dolor mollit ullamco aliqua. eu labore aliqua. sed officia enim qui nostrud eiusmod Excepteur aliquip quis officia in aliquip nostrud tempor proident, ea sed consequat. dolor aliqua. aliqua. in dolor in do ut eu mollit commodo nostrud amet, id Duis qui dolor velit sit cillum sit officia dolor cillum sunt in dolore consectetur tempor irure in sit dolore amet, fugiat nisi nulla sint exercitation cillum officia.
Sit velit ipsum commodo laboris cillum dolore aliquip sint laboris laborum. fugiat anim ipsum cupidatat est qui deserunt irure sit aliqua. veniam, id nisi sunt nisi occaecat mollit eiusmod et sint exercitation id Duis non sit irure cupidatat qui aliqua. do id tempor id in quis elit, fugiat dolore proident, irure do Excepteur qui non irure proident, nulla aliquip minim velit velit dolor voluptate adipisicing incididunt magna incididunt ad ad.
Laborum. in ullamco non consequat. Excepteur pariatur. fugiat eiusmod esse consectetur ea ex velit esse est voluptate tempor in dolor voluptate commodo magna consequat. nisi tempor et sit commodo ut aute cupidatat incididunt ut incididunt elit, ut ad veniam, mollit aute adipisicing consectetur ex id Excepteur ullamco esse laboris sit ad anim in amet, sunt.
Ut incididunt qui reprehenderit dolor Ut mollit tempor pariatur. tempor non commodo laboris Excepteur quis adipisicing aliqua. dolor incididunt Excepteur qui est esse sunt quis ex culpa ad consequat. voluptate sint cupidatat eiusmod minim enim sed aute Excepteur dolore incididunt cillum culpa cillum tempor pariatur. ipsum laborum. reprehenderit aliqua. Ut amet, ipsum amet, sunt veniam, sint Ut sint.
Ut in cillum consectetur adipisicing dolore Ut magna exercitation mollit pariatur. minim consequat. et in veniam, nulla enim ullamco sint Excepteur cupidatat consequat. ut sint fugiat tempor Duis eiusmod Excepteur officia qui anim eu proident, aute qui quis magna pariatur. tempor veniam, non exercitation irure dolor non proident, nisi qui pariatur. enim sint cupidatat fugiat elit, magna culpa in Duis exercitation deserunt et voluptate nostrud anim enim nisi proident, amet.
Est id ad elit, minim nulla velit incididunt ipsum deserunt sunt pariatur. sunt mollit voluptate laborum. mollit laboris voluptate dolore culpa ipsum labore in undefined voluptate cupidatat amet, sed in aliquip dolor tempor dolore in Ut dolor amet, eiusmod cupidatat in aliqua. ullamco incididunt aute Excepteur ad ullamco sit amet, mollit ex officia Duis.
Ex irure labore dolor aute reprehenderit ullamco elit, sit consectetur aliqua. non consectetur veniam, in dolor ipsum exercitation Lorem sed pariatur. laborum. consequat. culpa aliqua. Ut Duis laborum. Ut proident, aliquip adipisicing consectetur culpa magna do irure aute tempor quis incididunt cupidatat consequat. aliqua. dolor amet, dolor id nostrud est sit Excepteur mollit do mollit proident, veniam.
Ut non do deserunt irure incididunt veniam, veniam, occaecat nisi eiusmod ipsum nisi voluptate in officia undefined ex nisi velit nulla cillum est esse tempor consequat. do Ut qui cupidatat commodo fugiat culpa in ea cillum incididunt dolore pariatur. cupidatat Excepteur magna Ut proident, dolor Ut dolore id nostrud nulla mollit dolor veniam, consectetur tempor deserunt enim.
Sit in ut voluptate dolor deserunt occaecat enim aliqua. cupidatat anim enim sed labore qui culpa cillum cupidatat dolor esse dolor dolore commodo exercitation adipisicing qui consectetur adipisicing commodo fugiat nostrud proident, incididunt officia nisi eiusmod enim veniam, elit, occaecat in non in Ut laborum. ad ut reprehenderit ut commodo ex ex minim ad exercitation sint ex ullamco consequat. commodo culpa occaecat commodo nisi nulla labore Duis.
Amet, in ipsum occaecat exercitation qui laborum. undefined amet, officia reprehenderit laboris reprehenderit nulla ad velit dolor sint ex consequat. nulla enim occaecat in deserunt cupidatat cupidatat esse consectetur exercitation exercitation labore nisi consectetur exercitation nostrud nulla aliqua. esse laboris Lorem est mollit magna dolore sunt qui Lorem fugiat mollit consequat. ea reprehenderit reprehenderit et sed voluptate incididunt ullamco nisi consectetur non eiusmod qui nulla cupidatat.
Tempor qui voluptate mollit sed reprehenderit ut ipsum aliquip commodo proident, aliqua. exercitation laborum. occaecat ex deserunt do nostrud dolor Excepteur sit dolor in minim cupidatat nulla est culpa occaecat cillum pariatur. irure cupidatat sed est sit aute fugiat sint ipsum proident, aliquip ut aute sint aliquip ad nostrud nisi consequat. esse commodo laborum. Ut mollit ullamco eu undefined pariatur. velit dolore.
Proident, sit reprehenderit exercitation eu dolore Excepteur voluptate ea in dolor esse occaecat nulla laborum. sed aliquip nulla Duis adipisicing sunt in laborum. nostrud anim do nisi Duis undefined non eu dolore magna irure elit, eiusmod consequat. mollit aliquip dolor id minim id in aliquip ad deserunt dolore id est culpa deserunt culpa officia Excepteur laborum. esse.
In exercitation incididunt laborum. ea laborum. cupidatat ut in dolore nisi est laboris irure consequat. velit reprehenderit in dolor ipsum eu consequat. consequat. et laboris mollit dolore officia Excepteur irure eu cupidatat fugiat non ut Duis pariatur. enim eiusmod exercitation veniam, voluptate cillum elit, undefined sint Lorem Duis tempor deserunt quis consectetur in ut cupidatat consequat. ea ex.
Id adipisicing id tempor consectetur proident, quis laborum. deserunt ut et id veniam, proident, sunt ipsum non nostrud amet, qui ut laboris amet, exercitation cillum sed reprehenderit dolore labore cupidatat pariatur. magna dolore labore dolor id qui proident, enim veniam, aliquip laborum. ut fugiat dolore dolore sint cillum sit ut commodo in reprehenderit consectetur cillum Excepteur ex dolor nostrud ex minim.
Sed Ut ut esse dolor velit nostrud elit, cupidatat adipisicing cupidatat dolor labore dolore adipisicing eu consectetur incididunt Ut ut do aliqua. ex in laborum. eu cupidatat dolore adipisicing aliqua. qui dolore irure labore ex veniam, minim aliqua. cupidatat culpa est officia irure ea exercitation enim in ipsum culpa id adipisicing dolore ipsum aute exercitation ipsum irure anim veniam, dolor id veniam, ut ut sit minim.
Labore occaecat ut esse dolore eiusmod pariatur. tempor Lorem ullamco incididunt sint nisi eu cillum incididunt sunt qui exercitation Duis cupidatat qui proident, ad sit ad velit Lorem deserunt dolore ex ut enim aute nostrud dolore dolor do ea consectetur irure minim culpa ut dolor fugiat occaecat ut nostrud proident, sunt deserunt in ullamco consectetur minim sed commodo deserunt elit, Ut deserunt.
Duis ut dolor minim Ut adipisicing commodo pariatur. proident, dolor ut cupidatat in cupidatat sed et consequat. et laborum. minim enim fugiat occaecat tempor minim id veniam, sed ex ut aliquip ipsum dolore aliqua. exercitation ut laboris proident, ut ea ullamco Ut adipisicing tempor ullamco dolore sint in consequat. ex nisi in.
Anim Duis deserunt deserunt anim exercitation veniam, in id irure ut do ad consectetur tempor reprehenderit in eu adipisicing cupidatat labore laborum. culpa irure est anim exercitation dolor occaecat ut non adipisicing culpa ullamco tempor dolor esse exercitation magna et in dolore do voluptate reprehenderit tempor Excepteur magna dolor non cillum eiusmod dolore anim aute.
Ut sint reprehenderit culpa ut in tempor ea nulla veniam, in elit, irure consectetur dolor aliqua. ad tempor irure ipsum Ut nisi ullamco aliqua. veniam, officia qui occaecat dolore irure Ut reprehenderit mollit eu dolore adipisicing laboris deserunt dolore veniam, amet, velit dolore elit, anim sunt est ex laboris mollit culpa consequat. sint mollit consequat. in eiusmod incididunt ad exercitation esse.
Velit labore in aliquip id ut minim id ex consequat. labore officia Ut nulla commodo elit, sint Excepteur sed dolor eiusmod in reprehenderit aute occaecat nostrud proident, adipisicing enim irure velit dolor mollit officia undefined occaecat nisi nisi pariatur. nostrud labore amet, eiusmod aute id eu commodo dolor dolor pariatur. do reprehenderit aliquip exercitation cupidatat amet, proident, dolor aute esse voluptate.
Dolore irure ut officia et esse sed reprehenderit cupidatat consectetur cupidatat veniam, officia consequat. Excepteur ex ullamco qui sint non voluptate eiusmod irure in laborum. cupidatat dolore laboris adipisicing reprehenderit elit, fugiat in cupidatat quis consequat. ut quis nulla elit, in consectetur labore sed fugiat cillum enim Ut quis aute tempor cillum laboris ex sunt.
Consequat. do sunt eu enim elit, enim veniam, Duis amet, qui amet, officia sint labore dolore dolore eiusmod est qui reprehenderit consequat. aute Excepteur cillum id velit dolore mollit cupidatat minim cupidatat voluptate irure sunt eiusmod Ut ex adipisicing in consequat. enim magna aliqua. mollit laboris ad ex irure cillum esse consequat. non magna aliquip id amet, in esse adipisicing voluptate Duis Duis in.
Dolor consequat. nulla labore exercitation in commodo dolore fugiat anim cillum anim ea sint dolore deserunt ut occaecat aliqua. adipisicing ipsum culpa laborum. ullamco id quis deserunt ut pariatur. eu quis nulla enim commodo in non in quis cillum ullamco nulla ut officia esse ut id elit, dolore Duis enim ea sunt non reprehenderit ipsum dolore incididunt Duis id enim laboris amet.
Est ex amet, consectetur in nulla dolore nisi anim cupidatat sunt officia quis cupidatat amet, veniam, deserunt nisi magna ut aute amet, tempor enim est nulla adipisicing incididunt voluptate veniam, dolor mollit occaecat cupidatat eiusmod occaecat id nulla Lorem reprehenderit reprehenderit aliqua. fugiat labore Excepteur quis pariatur. quis adipisicing sint est dolore Lorem sed dolor est est enim aute irure laboris consectetur.
Sint velit sed incididunt amet, id culpa laboris cupidatat adipisicing culpa dolore deserunt in esse mollit anim sunt deserunt do nisi Ut qui anim ex quis tempor anim occaecat id anim tempor adipisicing Ut non tempor voluptate qui sed laboris id eiusmod aliquip occaecat minim mollit est nostrud aliquip ut nisi sunt sunt labore deserunt nulla incididunt Ut non voluptate cillum quis cupidatat commodo elit, magna.
Reprehenderit aliqua. et undefined cupidatat incididunt ad elit, labore commodo nostrud ullamco aute elit, Ut minim in eiusmod ullamco ullamco quis tempor reprehenderit consequat. magna aliquip ut proident, dolore eiusmod dolor magna commodo adipisicing ex tempor velit amet, reprehenderit nostrud non fugiat Excepteur ea id sunt enim Ut irure ut ipsum.
Consequat. pariatur. eu nulla laborum. aute enim veniam, sed qui ullamco id Ut labore officia non ipsum nostrud dolor dolor ex et consequat. enim id voluptate sit pariatur. aliqua. commodo eiusmod eu esse dolore reprehenderit elit, do ea ea cillum ut occaecat cupidatat enim culpa Excepteur in commodo Lorem et sed exercitation sit qui tempor irure tempor ut ea ullamco esse.
Cillum elit, est sunt Excepteur eu pariatur. dolor sunt minim qui ullamco consequat. ex do magna dolor occaecat enim id adipisicing magna consectetur ea sunt et dolore est non culpa id in sed elit, nulla fugiat ea cupidatat proident, esse minim in proident, nulla proident, amet, ex esse cillum Ut ex labore.
Sunt quis irure magna dolor ut exercitation pariatur. consequat. anim veniam, nulla nulla laborum. fugiat anim deserunt mollit deserunt consequat. pariatur. incididunt sed Lorem veniam, sit reprehenderit ullamco ex tempor cillum do Excepteur ad dolore sint ut do dolore quis undefined non dolore labore quis cupidatat labore et mollit undefined esse anim sed cillum ipsum sunt magna ut.
Commodo fugiat laborum. ea occaecat undefined dolor Ut tempor commodo eiusmod labore sed in in culpa Excepteur Duis velit labore dolor veniam, voluptate Excepteur anim amet, exercitation cillum amet, qui sed nostrud enim in dolore consequat. id proident, ut sit amet, sunt proident, commodo dolore dolor esse officia irure dolore aliquip in dolor aute magna deserunt quis aliqua.
Nulla id reprehenderit sint qui eu magna voluptate in commodo exercitation dolor adipisicing laborum. esse sed ullamco Duis sed aute velit culpa ea ea consequat. reprehenderit officia in sint in dolore veniam, proident, ex amet, sint cillum ut ad est est laboris est ullamco elit, enim nostrud esse culpa eu tempor dolore Duis.
Officia commodo reprehenderit incididunt non ipsum amet, deserunt in et officia ipsum tempor in sed Duis ullamco cupidatat Lorem ullamco dolor aliqua. reprehenderit elit, non do est ipsum ad eu quis ut laborum. commodo nulla et fugiat Excepteur consequat. sunt laboris adipisicing commodo et adipisicing officia reprehenderit nisi in do aute reprehenderit deserunt eu laboris occaecat eu et dolore nisi.
Ex sint ut enim velit adipisicing deserunt qui dolor aliqua. consectetur veniam, cupidatat consequat. aliquip officia irure culpa Excepteur ex qui laborum. et minim reprehenderit Ut ullamco sit aliquip qui in sit eiusmod proident, Ut ut ut adipisicing voluptate eiusmod reprehenderit do id amet, fugiat est labore ea ad Lorem eiusmod.
Aliquip dolore sunt occaecat non ut velit pariatur. minim consequat. anim laborum. elit, enim pariatur. culpa magna cupidatat aliqua. sint nulla ut laboris dolor ea velit ullamco labore eu dolore tempor ut id ut minim veniam, amet, nulla exercitation consectetur in et undefined occaecat ullamco aute laborum. aliqua. ea incididunt in velit elit, dolor incididunt irure ipsum in est ut deserunt sit ut tempor.
Voluptate consequat. consequat. est ut culpa velit incididunt sed quis eu qui occaecat dolor ad quis qui Duis non non ullamco dolor cillum dolor labore Ut qui minim occaecat irure officia esse cupidatat eu irure laboris quis ea tempor laboris consectetur officia officia incididunt dolore sunt sed qui in labore velit sed eiusmod esse.
Minim ea amet, in commodo fugiat laborum. cillum ad eiusmod esse qui do aliquip id esse id dolore laborum. anim aliqua. ea qui aute ea tempor est eu nisi nulla sunt incididunt Ut id minim ipsum incididunt labore sit exercitation laborum. irure velit Duis veniam, nisi officia ex in ex voluptate ea ex elit, mollit sunt cillum cillum.
Eiusmod quis dolore reprehenderit qui aliqua. fugiat dolor tempor elit, pariatur. elit, voluptate do consequat. consectetur aute laborum. sit incididunt fugiat sit veniam, tempor ullamco quis Ut commodo dolore cillum est anim occaecat nulla deserunt Ut ut ut enim dolor dolor reprehenderit Duis nostrud amet, Excepteur dolor dolore ut eiusmod sed ullamco quis laboris aute et aliquip ipsum ea non nostrud veniam.'''

filler_lines = filler_text.split('\n')

def random_text(num_paragraphs=3):
    return '\n\n'.join(random.choice(filler_lines) for i in range(num_paragraphs))
