#!/bin/bash
# The script that launches all other diary related scripts.

help_and_exit() {
    # TODO
    echo "Help not implemented yet."
    exit 0
}

usage_and_exit() {
    echo "usage: $(basename $0) command [option]... [argument]..." >&2
    echo "" >&2
    echo "basic commands:" >&2
    echo "" >&2
    echo " edit       edit the most recent entry or older entries" >&2
    echo " list       display the most recent entries or a given range of entries" >&2
    echo " new        start a new diary entry in the default editor" >&2
    echo " search     search diary entries for words or tags" >&2
    echo " wordcount  print wordcount information" >&2
    echo "" >&2
    echo "use \"$(basename $0) help\" for the full list of commands" >&2
    exit 1
}

# If no arguments then print usage and exit.
[[ $# == 0 ]] && usage_and_exit


# Find out which diary script was actually executed and then use the 
# corresponding subscripts. 
real_path=$(readlink -f $0)
real_path=${real_path%/*}

eval "diary-checklist() { '$real_path/diary-checklist'     \"\$@\"; }"
eval "diary-edit()      { '$real_path/diary-edit'          \"\$@\"; }"
eval "diary-format()    { '$real_path/diary-format'        \"\$@\"; }"
eval "diary-list()      { '$real_path/diary-search' --list \"\$@\"; }"
eval "diary-new-entry() { '$real_path/diary-new-entry'     \"\$@\"; }"
eval "diary-range()     { '$real_path/diary-range'         \"\$@\"; }"
eval "diary-search()    { '$real_path/diary-search'        \"\$@\"; }"
eval "diary-settings()  { '$real_path/diary-settings'      \"\$@\"; }"
eval "diary-wordcount() { '$real_path/diary-wordcount'     \"\$@\"; }"

export -f diary-checklist
export -f diary-edit
export -f diary-format
export -f diary-list
export -f diary-new-entry
export -f diary-range
export -f diary-search
export -f diary-settings
export -f diary-wordcount


# Source the default settings file and then source the user's settings file. 
source "$real_path/../config/diaryrc-default"

# The user's diaryrc file is looked for in the following locations and the 
# first existing file is used.
paths=( "$real_path/../config/diaryrc"   \
        "$real_path/../config/.diaryrc"  \
        "$HOME/diaryrc"                  \
        "$HOME/.diaryrc"                 )

for path in "${paths[@]}"; do
    if [[ -f "$path" ]]; then 
        source "$path"
        break
    fi
done



# Check for command.
command="$1"
shift

case "$command" in
    # TODO add a command called cd that can change the current dir easily to 
    # one of the commonly used diary directories (e.g. .diary, data, entries).
    checklist)
        diary-checklist "$@"
    ;;
    edit)
        diary-edit "$@" 
    ;;
    format)
        diary-format "$@"
    ;;
    help | -h | -help | --help)
        help_and_exit "$@" 
    ;;
    list | ls)
        diary-list "$@"
    ;;
    new-entry | new)
        diary-new-entry "$@" 
    ;;
    range)
        diary-range "$@"
    ;;
    search)
        diary-search "$@" 
    ;;
    settings)
        diary-settings "$@"
    ;;
    wordcount | wc)
        diary-wordcount "$@"
    ;;
    *)
        usage_and_exit "$@"
    ;;
esac
