#!/bin/bash
# Script to create a new entry with the default editor.

# Get the file path for a new entry.
entry_filename=$(diary-range --new)

# Use default editor on the filename.
eval "$diary_new_entry_default_editor \"$entry_filename\""
