#!/bin/bash
# Script to launch the default editor on a specified diary entry.

# If no arguments then use the last entry, otherwise use the given arguments 
# as arguments to diary-range and edit the first entry that it returns.
if [[ "$#" == 0 ]]; then 
    entry=$(diary-range '--range=-1::-1')
else
    entry=$(diary-range "$@" | head -q --lines=1)
fi

# Check that the file exists.
if [[ ! -f "$entry" ]]; then 
    echo "$(basename $0): file does not exist: \"$entry\"" >&2
    exit 1
fi

# Launch the default editor on it.
eval "$diary_edit_default_editor \"$entry\""
