#!/bin/bash
# Script to search diary entries for tags or text. 

do_search() {
    
    # Build search string.
    search_string="\($prefix$1$suffix\)"; shift
    for term in "$@"; do
        search_string="$search_string\|\($prefix$term$suffix\)"
    done


    local -i num_matches=0

    for entry in $(diary-range -r "$range"); do
        
        # If the entry contains the search string.
        if [[ -z "$search_string" ]] || \
                grep -qi "$search_string" "$entry"; then 

            # Print the entry using diary-format.
            diary-format -m --search="$search_string" "$entry"
            
            # Keep track of the number of matches found so far
            # and stop if the maximum search depth has been reached.
            let 'num_matches++'
            if [[ "$max_matches" ]] && (( num_matches >= max_matches )); then 
                echo "$num_matches entries found, max search depth reached."
                return
            fi

        fi

    done

    # Useful information to help the user work out why there were no matches. 
    if (( num_matches == 0 )); then 
    	echo "No entries found."
        echo "Range: $range"
        echo "Search term: $search_string"
    fi
}


# Process command line args.
#TODO: put defaults in diaryrc-default
print=
range="-500::-1"
max_matches=40
mode=tags
while true; do
    case "$1" in 
        -a | --all)
            range="::-1"
            max_matches=
            shift
        ;;
        -l | --list)
            mode=list
            max_matches=
            range="-30::-1"
            shift
        ;;
        -m)
            max_matches="$2"
            shift; shift
        ;;
        --max-matches=*)
            max_matches="${1#--max-matches=}"
            shift
        ;;
        -n) 
            range="-$2::-1"
            shift; shift
        ;;
        --number=*)
            range="-${1#--number=}::-1"
            shift
        ;;
        -p | --print)
            print=true
            shift
        ;;
        -r)
            range="$2"
            shift; shift
        ;;
        --range=*)
            range="${1#--range=}"
            shift
        ;;
        -t | --tags)
            mode=tags
            shift
        ;;
        -w | --words)
            mode=words
            shift
        ;;
        *)
            break
        ;;
    esac
done

# Set the prefixes and suffixes to surround each search term.
case "$mode" in
    list)
        prefix=
        suffix=
    ;;
    tags)
        prefix='#'
        suffix='\S*\>'
    ;;
    words)
        prefix='\b'
        suffix='\b'
    ;;
esac

# Do the search, either printing or displaying with less.
if [[ "$print" ]]; then 
    do_search "$@"
else
    do_search "$@" | less -R
fi
