#!/bin/bash
# Script to create a new entry with the default editor.

# Get the file path for a new entry.
entry_filename=$(diary-range --new)

# Get default editor and use it on $entry_filename.
editor=$(diary-settings get diary_new_entry_default_editor)
eval "$editor $entry_filename"
