#!/bin/bash
# The script that launches all other diary related scripts.

help_and_exit() {
    # TODO
    echo "Help not implemented yet."
    exit 0
}

usage_and_exit() {
    # TODO
    echo "Usage not implemented yet."
    exit 1
}

# Find out which diary script was actually executed and then use the 
# corresponding subscripts. 
real_path=$(readlink -f $0)
real_path=${real_path%/*}

eval "diary-checklist() { '$real_path/diary-checklist'     \$@; }"
eval "diary-edit()      { '$real_path/diary-edit'          \$@; }"
eval "diary-format()    { '$real_path/diary-format'        \$@; }"
eval "diary-list()      { '$real_path/diary-search' --list \$@; }"
eval "diary-new-entry() { '$real_path/diary-new-entry'     \$@; }"
eval "diary-range()     { '$real_path/diary-range'         \$@; }"
eval "diary-search()    { '$real_path/diary-search'        \$@; }"
eval "diary-settings()  { '$real_path/diary-settings'      \$@; }"
eval "diary-wordcount() { '$real_path/diary-wordcount'     \$@; }"

export -f diary-checklist
export -f diary-edit
export -f diary-format
export -f diary-list
export -f diary-new-entry
export -f diary-range
export -f diary-search
export -f diary-settings
export -f diary-wordcount


# Default action to be taken if the script is run with no arguments.
if [[ $# == 0 ]]; then 
    action="$(diary-settings get diary_default_action)"
    eval "$action"
    exit 0
fi


# Check for command.
command="$1"
shift

case "$command" in
    # TODO add a command called cd that can change the current dir easily to 
    # one of the commonly used diary directories (e.g. .diary, data, entries).
    checklist)
        diary-checklist "$@"
    ;;
    edit)
        diary-edit "$@" 
    ;;
    format)
        diary-format "$@"
    ;;
    help | -h | --help)
        help_and_exit "$@" 
    ;;
    list | ls)
        diary-list "$@"
    ;;
    new-entry | new)
        diary-new-entry "$@" 
    ;;
    range)
        diary-range "$@"
    ;;
    search)
        diary-search "$@" 
    ;;
    settings)
        diary-settings "$@"
    ;;
    wordcount | wc)
        diary-wordcount "$@"
    ;;
    *)
        usage_and_exit "$@"
    ;;
esac
