#!/bin/bash
# The script that launches all other diary related scripts.

help_and_exit() {
    # TODO
    echo "Help not implemented yet."
    exit 0
}

usage_and_exit() {
    echo "usage: $(basename $0) command [option]... [argument]..." >&2
    echo "" >&2
    echo "basic commands:" >&2
    echo "" >&2
    echo " edit       edit the most recent entry or older entries" >&2
    echo " list       display the most recent entries or a given range of entries" >&2
    echo " new        start a new diary entry in the default editor" >&2
    echo " search     search diary entries for words or tags" >&2
    echo " wordcount  print wordcount information" >&2
    echo "" >&2
    echo "use \"$(basename $0) help\" for the full list of commands" >&2
    exit 1
}

# If no arguments then print usage and exit.
[[ $# == 0 ]] && usage_and_exit


# Find out which diary script was actually executed and then use the 
# corresponding subscripts. 
real_path=$(readlink -f $0)
real_path=${real_path%/*}

eval "diary-chain()     { '$real_path/diary-chain'         \"\$@\"; }"
eval "diary-edit()      { '$real_path/diary-edit'          \"\$@\"; }"
eval "diary-format()    { '$real_path/diary-format'        \"\$@\"; }"
eval "diary-list()      { '$real_path/diary-search' --list \"\$@\"; }"
eval "diary-new-entry() { '$real_path/diary-new-entry'     \"\$@\"; }"
eval "diary-pyrange()   { '$real_path/diary-pyrange'       \"\$@\"; }"
eval "diary-range()     { '$real_path/diary-range'         \"\$@\"; }"
eval "diary-search()    { '$real_path/diary-search'        \"\$@\"; }"
eval "diary-wordcount() { '$real_path/diary-wordcount'     \"\$@\"; }"

export -f diary-chain
export -f diary-edit
export -f diary-format
export -f diary-list
export -f diary-new-entry
export -f diary-pyrange
export -f diary-range
export -f diary-search
export -f diary-wordcount

export real_path
export tags_file


# Source the default settings file and then source the user's settings file. 
source "$real_path/../config/diaryrc-default"

# The user's diaryrc file is looked for in the following locations and the 
# first existing file is used.
paths=( "$real_path/../config/diaryrc"   \
        "$real_path/../config/.diaryrc"  \
        "$HOME/diaryrc"                  \
        "$HOME/.diaryrc"                 )

for path in "${paths[@]}"; do
    if [[ -f "$path" ]]; then 
        source "$path"
        break
    fi
done

# Export the diary subdirectories.
export dir_diary
export dir_data="$dir_diary/data"
export dir_entries="$dir_data/entries"
export dir_checklists="$dir_data/checklists"
export dir_cache="$dir_diary/cache"
export dir_wordcounts="$dir_cache/wordcounts"
export dir_logs="$dir_data/logs"
export dir_chain="$dir_cache/chain"

# Export other relevant data.
export device_name

export diary_edit_default_editor
export diary_new_entry_default_editor

export header_minimum_width
export long_date_format
export short_date_format
export very_short_date_format
export pad_char
export metadata_colour
export pad_colour
export end_colour

export search_print_entries
export search_default_range
export search_default_max_matches


# Check for command.
command="$1"
shift

case "$command" in
    chain)
        diary-chain "$@"
    ;;
    edit)
        diary-edit "$@" 
    ;;
    format)
        diary-format "$@"
    ;;
    help | -h | -help | --help)
        help_and_exit "$@" 
    ;;
    list | ls)
        diary-list "$@"
    ;;
    new-entry | new)
        diary-new-entry "$@" 
    ;;
    pyrange)
        diary-pyrange "$@"
    ;;
    range)
        diary-range "$@"
    ;;
    search)
        diary-search "$@" 
    ;;
    --version)
        echo "No version number is currently available."
    ;;
    wordcount | wc)
        diary-wordcount "$@"
    ;;
    *)
        usage_and_exit "$@"
    ;;
esac
