#!/bin/bash
# Script to create a new entry with the default editor. Accepts zero arguments 
# or a single timestamp used as the timestamp for the new entry.

# Get the file path for a new entry.
entry_filename=$(diary-range --new $1)

# Create directory(s) if necessary.
entry_directory="${entry_filename%/*}"
mkdir -p "$entry_directory"

# Use default editor on the filename.
eval "$diary_new_entry_default_editor \"$entry_filename\""
