#!/bin/bash

real_path=$(readlink -f $0)
real_path=${real_path%/*}

# Check for command.
command="$1"
shift

case "$command" in
    edit)
        python3 "$real_path/diary_edit.py" "$@" 
    ;;
    list | ls)
        python3 "$real_path/diary_list.py" "$@"
    ;;
    new)
        python3 "$real_path/diary_edit.py" --new "$@" 
    ;;
    search)
        python3 "$real_path/diary_search.py" "$@" 
    ;;
esac
